### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by PolishLyfe** [yugecin/opsu-dance#112]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_65
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:662)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:600)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:322)
	at itdelatrisu.opsu.Container.close_sub(Container.java:122)
	at itdelatrisu.opsu.Container.start(Container.java:73)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
```

**Comment by Chaaoos** [comment]
FeelsNullPointerExceptionMan

**Comment by yugecin** [comment]
old exception handling, cannot determine cause
