### ISSUE TITLE
checkpoint error in game

### ISSUE THREAD

**Issue by AwesomeGamer89** [yugecin/opsu-dance#115]
Something bad happend while playing
java.lang.ArrayIndexOutOfBoundsException: -1
	at itdelatrisu.opsu.states.Game.loadCheckpoint(Game.java:344)
	at itdelatrisu.opsu.states.Game.keyPressed(Game.java:1127)
	at org.newdawn.slick.state.StateBasedGame.keyPressed(StateBasedGame.java:445)
	at org.newdawn.slick.Input.poll(Input.java:1212)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:98)
	at itdelatrisu.opsu.Container.start(Container.java:68)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)

**Comment by yugecin** [comment]
Fix ready 2c2ba31
