### ISSUE TITLE
Could not connect to database: 'C:\Users\mamath\Desktop\opsu-dance-master\kkk\.opsu.db'.

### ISSUE THREAD

**Issue by WolfSiZe** [yugecin/opsu-dance#116]
**OS:** Windows 8.1 (amd64)
**JRE:** 1.8.0_111
**Error:** `Could not connect to database: 'C:\Users\mamath\Desktop\opsu-dance-master\kkk\.opsu.db'.`
**Stack trace:**
```
java.sql.SQLException: No suitable driver found for jdbc:sqlite:C:\Users\mamath\Desktop\opsu-dance-master\kkk\.opsu.db
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:99)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:46)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:175)
```

**Comment by yugecin** [comment]
you're missing the sqlite dependency
maven:
```
<dependency>
	<groupId>org.xerial</groupId>
	<artifactId>sqlite-jdbc</artifactId>
	<version>3.8.10.2</version>
</dependency>
```
