### ISSUE TITLE
Could not connect to database: '.\.opsu_scores.db'.

### ISSUE THREAD

**Issue by Tmuru321** [yugecin/opsu-dance#124]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_121
**Error:** `Could not connect to database: '.\.opsu_scores.db'.`
**Stack trace:**
```
java.sql.SQLException: opening db: '.\.opsu_scores.db': Acceso denegado
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:203)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at itdelatrisu.opsu.db.DBController.createConnection(DBController.java:65)
	at itdelatrisu.opsu.db.ScoreDB.init(ScoreDB.java:88)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:47)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:175)
```

**Comment by yugecin** [comment]
Where are you running the program? Do you have write access to the folder or only as administrator?

**Comment by Tmuru321** [comment]
im running the program in windows 10 and i dont understand the second question

**Comment by Tmuru321** [comment]
I do not understand very well the question
Like that where I'm running from?

**Comment by Tmuru321** [comment]
I do not know how the hell I made it work but then stopped doing it

**Comment by Tmuru321** [comment]
why this happens tom me

**Comment by yugecin** [comment]
try with latest release https://github.com/yugecin/opsu-dance/releases/latest
