### ISSUE TITLE
Game.update() failure. 

### ISSUE THREAD

**Issue by jamakakaja1** [yugecin/opsu-dance#127]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_121
**OpenGL Version:** 4.0.0 - Build 10.18.10.4358 (Intel)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:98)
	at itdelatrisu.opsu.Container.start(Container.java:68)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at itdelatrisu.opsu.objects.curves.CircumscribedCircle.<init>(CircumscribedCircle.java:117)
	at itdelatrisu.opsu.beatmap.HitObject.getSliderCurve(HitObject.java:445)
	at itdelatrisu.opsu.beatmap.tpSlider.<init>(BeatmapDifficultyCalculator.java:526)
	at itdelatrisu.opsu.beatmap.tpHitObject.<init>(BeatmapDifficultyCalculator.java:336)
	at itdelatrisu.opsu.beatmap.BeatmapDifficultyCalculator.calculate(BeatmapDifficultyCalculator.java:146)
	at itdelatrisu.opsu.states.SongMenu.calculateStarRatings(SongMenu.java:1652)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1415)
	at itdelatrisu.opsu.states.SongMenu.update(SongMenu.java:755)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
```
Map: https://osu.ppy.sh/s/507506

**Comment by yugecin** [comment]
same as #125
