### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Tmuru321** [yugecin/opsu-dance#128]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_121
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:662)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:600)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:322)
	at itdelatrisu.opsu.Container.close_sub(Container.java:122)
	at itdelatrisu.opsu.Container.start(Container.java:73)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
```

**Comment by Tmuru321** [comment]
why this happens tom me

**Comment by Herobrine59** [comment]
that happens to me too.
