### ISSUE TITLE
Failed to load file 'C:\Users\Dell.Dell-PC\AppData\Local\osu!\Skins\Black+2014\normal-slidertick.wav'.

### ISSUE THREAD

**Issue by poipoikiju8jujujujujihyujikl** [yugecin/opsu-dance#129]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_101
**OpenGL Version:** 4.5.0 NVIDIA 372.70 (NVIDIA Corporation)
**Error:** `Failed to load file 'C:\Users\Dell.Dell-PC\AppData\Local\osu!\Skins\Black+2014\normal-slidertick.wav'.`
**Stack trace:**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:99)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:239)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:157)
```

**Comment by Chaaoos** [comment]
Doesn't support .wav files?
