### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AwesomeGamer89** [yugecin/opsu-dance#133]
at itdelatrisu.opsu.beatmap.tpSlider.<init>(BeatmapDifficultyCalculator.java:526)
	at itdelatrisu.opsu.beatmap.tpHitObject.<init>(BeatmapDifficultyCalculator.java:336)
	at itdelatrisu.opsu.beatmap.BeatmapDifficultyCalculator.calculate(BeatmapDifficultyCalculator.java:146)
	at itdelatrisu.opsu.states.SongMenu.calculateStarRatings(SongMenu.java:1652)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1415)
	at itdelatrisu.opsu.states.SongMenu.mouseClicked(SongMenu.java:924)
	at org.newdawn.slick.state.StateBasedGame.mouseClicked(StateBasedGame.java:488)
	at org.newdawn.slick.Input.fireMouseClicked(Input.java:1563)
	at org.newdawn.slick.Input.considerDoubleClick(Input.java:1141)
	at org.newdawn.slick.Input.poll(Input.java:1265)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:98)
	at itdelatrisu.opsu.Container.start(Container.java:68)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)

**Comment by yugecin** [comment]
do you have the full thing? like the messages that actually says what to exception was?

**Comment by yugecin** [comment]
see #295
