### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by kbkcld** [yugecin/opsu-dance#140]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_91
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:662)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:600)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:322)
	at itdelatrisu.opsu.Container.close_sub(Container.java:122)
	at itdelatrisu.opsu.Container.start(Container.java:73)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
```

**Comment by vistafan12** [comment]
Fixed. https://github.com/yugecin/opsu-dance/commit/3c5dc97c387712d8077d1de5e5a373e5a750ac60

**Comment by yugecin** [comment]
this issue had nothing to do with that

**Comment by vistafan12** [comment]
Ohh ok
