### ISSUE TITLE
its crashing for no reason

### ISSUE THREAD

**Issue by BillTheBillBill** [yugecin/opsu-dance#149]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_131
**OpenGL Version:** 4.5.0 NVIDIA 384.76 (NVIDIA Corporation)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalDeleteSources(IJ)V
	at org.lwjgl.openal.AL10.nalDeleteSources(Native Method)
	at org.lwjgl.openal.AL10.alDeleteSources(AL10.java:766)
	at itdelatrisu.opsu.audio.MusicController.destroyOpenAL(MusicController.java:490)
	at itdelatrisu.opsu.audio.MusicController.reset(MusicController.java:455)
	at itdelatrisu.opsu.Container.close_sub(Container.java:134)
	at itdelatrisu.opsu.Container.start(Container.java:73)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
```

**Comment by BillTheBillBill** [comment]
nvm i fixed it
