### ISSUE TITLE
Something bad happend while playing

### ISSUE THREAD

**Issue by Nitility** [yugecin/opsu-dance#162]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_144
**OpenGL Version:** 4.5.0 NVIDIA 385.69 (NVIDIA Corporation)
**Error:** `Something bad happend while playing`
**Stack trace:**
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at itdelatrisu.opsu.Options$GameOption$11.clickListItem(Options.java:343)
	at yugecin.opsudance.ui.OptionsOverlay.mousePressed(OptionsOverlay.java:377)
	at itdelatrisu.opsu.states.OptionsMenu.mousePressed(OptionsMenu.java:201)
	at org.newdawn.slick.state.StateBasedGame.mousePressed(StateBasedGame.java:499)
	at org.newdawn.slick.Input.poll(Input.java:1249)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:98)
	at itdelatrisu.opsu.Container.start(Container.java:68)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
```

**Comment by yugecin** [comment]
should be fixed with the new option menu when 0.5.0 is released
