### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by YouCanNotKnow** [yugecin/opsu-dance#165]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_144
**OpenGL Version:** 4.5.0 - Build 22.20.16.4771 (Intel)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:98)
	at itdelatrisu.opsu.Container.start(Container.java:68)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
Caused by: java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Unknown Source)
	at java.nio.DirectFloatBufferU.put(Unknown Source)
	at itdelatrisu.opsu.render.CurveRenderState.fillCone(CurveRenderState.java:364)
	at itdelatrisu.opsu.render.CurveRenderState.createVertexBuffer(CurveRenderState.java:304)
	at itdelatrisu.opsu.render.CurveRenderState.initFBO(CurveRenderState.java:119)
	at itdelatrisu.opsu.render.CurveRenderState.<init>(CurveRenderState.java:108)
	at itdelatrisu.opsu.objects.curves.Curve.draw(Curve.java:152)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1617)
	at itdelatrisu.opsu.states.Game.render(Game.java:634)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
This happened when I launched the winning aspire map

**Comment by Kontorted** [comment]
Dont bring this up here, go to the master opsu repository : https://github.com/itdelatrisu/opsu
and make the issue there
