### ISSUE TITLE
i download opsu 0.4.1 and this happens!

### ISSUE THREAD

**Issue by Culjoo** [yugecin/opsu-dance#170]
**Version:** 0.4.1
**Build date:** 2016-12-13 00:02
**OS:** Windows 10 (x86)
**JRE:** 1.8.0_144
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:662)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:600)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:322)
	at itdelatrisu.opsu.Container.close_sub(Container.java:122)
	at itdelatrisu.opsu.Container.start(Container.java:73)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
```

pls helpp T_T

**Comment by scaredosu** [comment]
i have the same problem
