### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by jylescoad-ward** [yugecin/opsu-dance#182]
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 10 (amd64)
**JRE:** 1.8.0_172
**OpenGL Version:** 4.6.0 NVIDIA 388.13 (NVIDIA Corporation)
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.db.BeatmapDB.insert(BeatmapDB.java:273)
	at itdelatrisu.opsu.beatmap.BeatmapParser.parseDirectories(BeatmapParser.java:202)
	at itdelatrisu.opsu.beatmap.BeatmapParser.parseAllFiles(BeatmapParser.java:84)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:151)
```

**Comment by yugecin** [comment]
that's weird, can you look in the log file and see if there's any errors that preceded this?
