### ISSUE TITLE
*** Unhandled NullPointerException: update/render error

### ISSUE THREAD

**Issue by GamerNoTitle** [yugecin/opsu-dance#261]
java.lang.NullPointerException
	at org.newdawn.slick.openal.SoundStore.setMusicPitch(Unknown Source)
	at org.newdawn.slick.Music.setPitch(Unknown Source)
	at itdelatrisu.opsu.audio.MusicController.setPitch(Unknown Source)
	at itdelatrisu.opsu.states.game.PauseOverlay.backToSongMenu(Unknown Source)
	at itdelatrisu.opsu.states.game.PauseOverlay.checkButtonClick(Unknown Source)
	at itdelatrisu.opsu.states.game.PauseOverlay.mouseReleased(Unknown Source)
	at yugecin.opsudance.core.input.Input.dispatch(Unknown Source)
	at yugecin.opsudance.core.input.Input.poll(Unknown Source)
	at yugecin.opsudance.core.DisplayContainer.run(Unknown Source)
	at yugecin.opsudance.OpsuDance.rungame(Unknown Source)
	at yugecin.opsudance.OpsuDance.start(Unknown Source)
	at yugecin.opsudance.core.Entrypoint.main(Unknown Source)

> DisplayContainer dump
OpenGL version: 4.5.0 - Build 25.20.100.6323(Intel)
> BaseOpsuState dump
isDirty: false

**Comment by ssCherry** [comment]
same

**Comment by Dylstructor** [comment]
It is because the storyboard mode is broke rn ### OOF
