### ISSUE TITLE
*** Unhandled NullPointerException: startup failure

### ISSUE THREAD

**Issue by xsCalamity** [yugecin/opsu-dance#262]
at itdelatrisu.opsu.db.BeatmapDB.init(Unknown Source)
	at itdelatrisu.opsu.db.DBController.init(Unknown Source)
	at yugecin.opsudance.OpsuDance.initDatabase(Unknown Source)
	at yugecin.opsudance.OpsuDance.start(Unknown Source)
	at yugecin.opsudance.core.Entrypoint.main(Unknown Source)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: null(null)
state is null!

```

**Comment by yugecin** [comment]
full trace (thx to #281)
```
java.lang.NullPointerException
	at itdelatrisu.opsu.ui.Fonts.wrap(Fonts.java:154)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.recalculateDimensions(BubNotifState.java:197)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.<init>(BubNotifState.java:187)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.<init>(BubNotifState.java:156)
	at yugecin.opsudance.core.state.specialstates.BubNotifState.send(BubNotifState.java:125)
	at yugecin.opsudance.core.errorhandling.ErrorHandler.softErr(ErrorHandler.java:86)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:139)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:44)
	at yugecin.opsudance.OpsuDance.initDatabase(OpsuDance.java:86)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:38)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)
```

**Comment by yugecin** [comment]
see #292
