### ISSUE TITLE
Startup Failure

### ISSUE THREAD

**Issue by Fliqa** [yugecin/opsu-dance#264]
java.lang.NullPointerException
	at itdelatrisu.opsu.ui.Fonts.wrap(Fonts.java:154)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.recalculateDimensions(BubNotifState.java:197)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.<init>(BubNotifState.java:187)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.<init>(BubNotifState.java:156)
	at yugecin.opsudance.core.state.specialstates.BubNotifState.send(BubNotifState.java:125)
	at yugecin.opsudance.core.errorhandling.ErrorHandler.softErr(ErrorHandler.java:86)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:139)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:44)
	at yugecin.opsudance.OpsuDance.initDatabase(OpsuDance.java:86)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:38)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

> DisplayContainer dump
OpenGL version: null(null)
state is null!

**Comment by yugecin** [comment]
see #292
