### ISSUE TITLE
*** Unhandled NullPointerException: update/render error

### ISSUE THREAD

**Issue by NameTheWorst** [yugecin/opsu-dance#267]
update/render error

**ver** 0.5.1
**os** Windows 10 (x86)
**jre** 1.8.0_201 (Oracle Corporation)
**trace**
```
java.lang.NullPointerException
	at yugecin.opsudance.sbv2.MoveStoryboard.onPreRenderUpdate(MoveStoryboard.java:101)
	at yugecin.opsudance.core.state.OverlayOpsuState.preRenderUpdate(OverlayOpsuState.java:41)
	at yugecin.opsudance.core.state.ComplexOpsuState.preRenderUpdate(ComplexOpsuState.java:127)
	at itdelatrisu.opsu.states.game.Game.preRenderUpdate(Game.java:732)
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:278)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:72)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:50)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: 4.6.13544 Compatibility Profile Context 25.20.15011.1004(ATI Technologies Inc.)
> BaseOpsuState dump
isDirty: false

```

**Comment by yugecin** [comment]
uncheck 'enable storyboard' in the options, it's not working atm
