### ISSUE TITLE
*** Unhandled NullPointerException: update/render error

### ISSUE THREAD

**Issue by deR1t** [yugecin/opsu-dance#270]
update/render error

**ver** 0.5.1
**os** Windows 10 (amd64)
**jre** 1.8.0_201 (Oracle Corporation)
**trace**
```
java.lang.NullPointerException
	at yugecin.opsudance.ui.OptionsOverlay.renderSearch(OptionsOverlay.java:703)
	at yugecin.opsudance.ui.OptionsOverlay.render(OptionsOverlay.java:335)
	at itdelatrisu.opsu.states.game.Game.render(Game.java:726)
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:279)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:72)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:50)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: 4.6.0 NVIDIA 418.96(NVIDIA Corporation)
> BaseOpsuState dump
isDirty: false

```
_(I get this error when I enable the storyboard editor and play any map.)_

**Comment by yugecin** [comment]
yeah the storyboard editor is unusable at the moment, sorry

**Comment by deR1t** [comment]
okay, thanks!
