### ISSUE TITLE
*** Unhandled NoSuchFileException: Failed to unpack natives. opsu!dance will close.

### ISSUE THREAD

**Issue by CINNermon** [yugecin/opsu-dance#272]
java.nio.file.NoSuchFileException: C:\Users\Mr.%20Molasses\Downloads\Natives
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
	at java.nio.file.Files.createDirectory(Unknown Source)
	at yugecin.opsudance.core.NativeLoader.loadNatives(Unknown Source)
	at yugecin.opsudance.core.Entrypoint.main(Unknown Source)

displayContainer is null!

**Comment by yugecin** [comment]
try [latest version](https://github.com/yugecin/opsu-dance/releases/latest)

**Comment by CINNermon** [comment]
thank you 🍔
