### ISSUE TITLE
Maps with storyboards and the storyboard editor crashes opsu!dance

### ISSUE THREAD

**Issue by JG-GIT** [yugecin/opsu-dance#277]
Logs for both instances are here.
Storyboard + Editor:
update/render error

java.lang.NullPointerException
	at yugecin.opsudance.ui.OptionsOverlay.renderSearch(OptionsOverlay.java:703)
	at yugecin.opsudance.ui.OptionsOverlay.render(OptionsOverlay.java:335)
	at itdelatrisu.opsu.states.game.Game.render(Game.java:726)
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:279)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:72)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:50)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

> DisplayContainer dump
OpenGL version: 4.5.13399 Compatibility Profile Context 15.201.1151.0(ATI Technologies Inc.)
> BaseOpsuState dump
isDirty: false

I have no idea how this error occurred, but it happened as well after opsu!dance crashed while trying to load Aleph 0.

Could not launch. Either opsu! is already running or a different program uses port 49250.
You can change the port opsu! uses by editing the 'Port' field in the .opsu.cfg configuration file.
If that still does not resolve the problem, you can set 'NoSingleInstance' to 'true', but this is not recommended.

java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at yugecin.opsudance.OpsuDance.isOtherInstanceRunning(OpsuDance.java:123)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:33)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

> DisplayContainer dump
OpenGL version: null(null)
state is null!

**Comment by JG-GIT** [comment]
Well, it seems like the storyboard issue actually doesn't exist.
But the storyboard issue previously conveyed was actually caused by negative sliders.

**Comment by JG-GIT** [comment]
Also, I can't find the Draw Experimental Sliders option to stop this from happening.

**Comment by yugecin** [comment]
I think "experimental sliders" are an option of the normal opsu and not opsu!dance though

**Comment by JG-GIT** [comment]
Also, the storyboard isn't actually added {consistent with the actual opsu! release}, so maps such as Aleph-0 [unplayable in opsu!dance, due to lack of Draw Experimental Sliders] and Disconnected Hardkore [playable, but every circle {0-length slider} related to the storyboard doesn't get inserted into the map, leading to the Cursordance bot clicking nothing] are much more difficult to play properly.
