### ISSUE TITLE
error with opsu!dance

### ISSUE THREAD

**Issue by KoldW** [yugecin/opsu-dance#282]
i open opsu-dance-0.5.1 and i get a log something like this

**java.lang.NullPointerException
	at itdelatrisu.opsu.ui.Fonts.wrap(Fonts.java:154)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.recalculateDimensions(BubNotifState.java:197)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.<init>(BubNotifState.java:187)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.<init>(BubNotifState.java:156)
	at yugecin.opsudance.core.state.specialstates.BubNotifState.send(BubNotifState.java:125)
	at yugecin.opsudance.core.errorhandling.ErrorHandler.softErr(ErrorHandler.java:86)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:139)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:44)
	at yugecin.opsudance.OpsuDance.initDatabase(OpsuDance.java:86)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:38)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

> DisplayContainer dump
OpenGL version: null(null)
state is null!**

is there something wrong with my java, or something that needs a fix?

**Comment by yugecin** [comment]
probably the path where you're running from, can you tell me the full path where you put the jar?

**Comment by KoldW** [comment]
from downloads

**Comment by KoldW** [comment]
and is there something wrong that opsudance cannot run?

**Comment by KoldW** [comment]
i moved from downloads to oringinal osu! folder and i get this
java.lang.Exception
	at yugecin.opsudance.core.Entrypoint.setRuntimeInfo(Entrypoint.java:114)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:33)

displayContainer is null!

**Comment by KoldW** [comment]
oh, i know now, thanks @yugecin for help!
