### ISSUE TITLE
*** Unhandled NullPointerException: startup failure

### ISSUE THREAD

**Issue by DemonEclipSe** [yugecin/opsu-dance#284]
startup failure

**ver** 0.5.1
**os** Windows 10 (x86)
**jre** 1.8.0_221 (Oracle Corporation)
**trace**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.ui.Fonts.wrap(Fonts.java:154)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.recalculateDimensions(BubNotifState.java:197)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.<init>(BubNotifState.java:187)
	at yugecin.opsudance.core.state.specialstates.BubNotifState$Notification.<init>(BubNotifState.java:156)
	at yugecin.opsudance.core.state.specialstates.BubNotifState.send(BubNotifState.java:125)
	at yugecin.opsudance.core.errorhandling.ErrorHandler.softErr(ErrorHandler.java:86)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:139)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:44)
	at yugecin.opsudance.OpsuDance.initDatabase(OpsuDance.java:86)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:38)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: null(null)
state is null!

```

**Comment by yugecin** [comment]
make sure the path where you're running from doesn't have special characters or the `!` character

**Comment by yugecin** [comment]
see #292
