### ISSUE TITLE
getting the same error everytimes

### ISSUE THREAD

**Issue by emberprotogen** [yugecin/opsu-dance#299]
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (table beatmaps has 49 columns but 47 values were supplied)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.throwex(DB.java:868)
	at org.sqlite.core.NativeDB.prepare(Native Method)
	at org.sqlite.core.DB.prepare(DB.java:211)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:40)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:29)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:18)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:47)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:254)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
	at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:119)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:45)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:39)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

> DisplayContainer dump
OpenGL version: null(null)
state is null
tNextState is null
loading sound: none
playing map: null

**Comment by yugecin** [comment]
your .opsu.db file was made/usedby opsu! and cannot be used for opsu!dance, either remove/rename it or run opsu!dance in a different directory
