### ISSUE TITLE
*** Unhandled NullPointerException: update/render error

### ISSUE THREAD

**Issue by waszup** [yugecin/opsu-dance#302]
update/render error

**ver** 0.5.1
**os** Windows 10 (amd64)
**jre** 1.8.0_221 (Oracle Corporation)
**trace**
```
java.lang.NullPointerException
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:235)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:75)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:53)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: 4.5.0 - Build 25.20.100.6446(Intel)
state is Splash
> BaseOpsuState dump
isDirty: false
> Splash dump
progress: parsing beatmaps
< DisplayContainer
tNextState is null
loading sound: none
playing map: null

```

**Comment by yugecin** [comment]
wow that's weird, does this happen consistently?

**Comment by waszup** [comment]
Yes i keep clicking on ignore and continue but it still show error
