### ISSUE TITLE
when changing skins it crashes

### ISSUE THREAD

**Issue by myaccountgotdeleted** [yugecin/opsu-dance#304]
Hello
I know i have posted another issue before but now it is crashing with skins that previously worked before (I think it is the audio files)
I think the problem is it is trying to read a non existent MP3 file as you can see in the log
>Also I'm curious how you did the 50 cursor replays thing because I'm working on a 8 player one featuring all of them as me!
Here is the crash error ⬇
```javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:103)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:226)
	at yugecin.opsudance.skinning.SkinService.reloadSkin(SkinService.java:46)
	at yugecin.opsudance.options.Options$10.clickListItem(Options.java:201)
	at yugecin.opsudance.ui.OptionsOverlay$MyDropdownMenu.itemSelected(OptionsOverlay.java:1390)
	at itdelatrisu.opsu.ui.DropdownMenu.mouseReleased(DropdownMenu.java:289)
	at yugecin.opsudance.core.input.Input.dispatch(Input.java:199)
	at yugecin.opsudance.core.input.Input.poll(Input.java:127)
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:220)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:75)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:53)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

> DisplayContainer dump
OpenGL version: 4.6.0 NVIDIA 441.41(NVIDIA Corporation)
state is MainMenu
> BaseOpsuState dump
isDirty: false
> MainMenu dump
< DisplayContainer
tNextState is null
overlay MainMenu
> options overlay is active
hoverOption is Skin
< DisplayContainerloading sound: D:\osu2015\Skins\clear\combobreak.mp3, progress: 2
playing map:  setid 0 beatmapid 0 name Jingle Punks - On the Bach []
 at time 11282
```
and here is the log: https://pastebin.com/raw/HdVNLvZc
i had to add it to a pastebin because it was too long to fit in here

**Comment by myaccountgotdeleted** [comment]
I fixed it by removing some audio files but i'm still curious how you did the 50 cursor replays thing anyway I will close this as it is irrelevant

**Comment by yugecin** [comment]
there's a `replaystuff` and `kockout` branch, where the code is for the replay stuff. I don't have any prebuilts atm.

**Comment by myaccountgotdeleted** [comment]
I will look into it
