### ISSUE TITLE
*** Unhandled NullPointerException: update/render error

### ISSUE THREAD

**Issue by MrBacon534** [yugecin/opsu-dance#315]
update/render error

**ver** 0.5.1
**os** Windows 10 (x86)
**jre** 1.8.0_251 (Oracle Corporation)
**trace**
```
java.lang.NullPointerException
	at yugecin.opsudance.sbv2.MoveStoryboard.onPreRenderUpdate(MoveStoryboard.java:101)
	at yugecin.opsudance.core.state.OverlayOpsuState.preRenderUpdate(OverlayOpsuState.java:41)
	at yugecin.opsudance.core.state.ComplexOpsuState.preRenderUpdate(ComplexOpsuState.java:127)
	at itdelatrisu.opsu.states.game.Game.preRenderUpdate(Game.java:733)
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:280)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:75)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:53)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: 4.6.0 - Build 26.20.100.7926(Intel)
state is Game
> BaseOpsuState dump
isDirty: false
> Game dump
beatmap:  setid 718825 beatmapid 1518125 name Luschka - Kami no Kotoba [I rewind it towards days that will not change.]
objectidx: 0
time: 0ms
< DisplayContainer
tNextState is null
loading sound: none
playing map:  setid 718825 beatmapid 1518125 name Luschka - Kami no Kotoba [I rewind it towards days that will not change.]
 at time 0 

```

**Comment by yugecin** [comment]
disable 'storyboard' in the options menu, it doesn't work atm
