### ISSUE TITLE
never had a program try so hard to stop me from using it.

### ISSUE THREAD

**Issue by piee-kun** [yugecin/opsu-dance#323]
1. it doesnt support openjdk. the program simply refuses to load with openjdk 11. installing jre8u261 made it load.

2. for some reason, opsu just refuses to let me into song select. no matter what i do, the program is oblivious to my mouse clicks on the logo.

3. keeps spitting out `PNGImageData failed to read the data` errors in the log. 
`[   27719] WARN: class org.newdawn.slick.opengl.PNGImageData failed to read the data
[        ] WARN: java.io.IOException: unsupported interlace method
[        ] WARN:  at org.newdawn.slick.opengl.PNGDecoder.readIHDR(PNGDecoder.java:620)
[        ] WARN:  at org.newdawn.slick.opengl.PNGDecoder.<init>(PNGDecoder.java:116)
[        ] WARN:  at org.newdawn.slick.opengl.PNGImageData.loadImage(PNGImageData.java:81)
[        ] WARN:  at org.newdawn.slick.opengl.CompositeImageData.loadImage(CompositeImageData.java:62)
[        ] WARN:  at org.newdawn.slick.opengl.CompositeImageData.loadImage(CompositeImageData.java:43)
[        ] WARN:  at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:292)
[        ] WARN:  at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:254)
[        ] WARN:  at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:187)
[        ] WARN:  at org.newdawn.slick.Image.<init>(Image.java:222)
[        ] WARN:  at org.newdawn.slick.Image.<init>(Image.java:196)
[        ] WARN:  at org.newdawn.slick.Image.<init>(Image.java:184)
[        ] WARN:  at org.newdawn.slick.Image.<init>(Image.java:162)
[        ] WARN:  at itdelatrisu.opsu.GameImage.loadImageSingle(GameImage.java:826)
[        ] WARN:  at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:711)
[        ] WARN:  at itdelatrisu.opsu.GameImage.getImage(GameImage.java:611)
[        ] WARN:  at yugecin.opsudance.render.TextureData.<init>(TextureData.java:18)
[        ] WARN:  at yugecin.opsudance.ui.cursor.NewestCursor.<init>(NewestCursor.java:29)
[        ] WARN:  at yugecin.opsudance.core.DisplayContainer.reinitCursor(DisplayContainer.java:181)
[        ] WARN:  at yugecin.opsudance.core.DisplayContainer.reinit(DisplayContainer.java:166)
[        ] WARN:  at yugecin.opsudance.core.DisplayContainer.postInitGL(DisplayContainer.java:508)
[        ] WARN:  at yugecin.opsudance.core.DisplayContainer.setDisplayMode(DisplayContainer.java:476)
[        ] WARN:  at yugecin.opsudance.core.DisplayContainer.updateDisplayMode(DisplayContainer.java:440)
[        ] WARN:  at yugecin.opsudance.core.DisplayContainer.updateDisplayMode(DisplayContainer.java:421)
[        ] WARN:  at yugecin.opsudance.options.Options$8.clickListItem(Options.java:158)
[        ] WARN:  at yugecin.opsudance.ui.OptionsOverlay$MyDropdownMenu.itemSelected(OptionsOverlay.java:1390)
[        ] WARN:  at itdelatrisu.opsu.ui.DropdownMenu.mouseReleased(DropdownMenu.java:289)
[        ] WARN:  at yugecin.opsudance.core.input.Input.dispatch(Input.java:199)
[        ] WARN:  at yugecin.opsudance.core.input.Input.poll(Input.java:127)
[        ] WARN:  at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:220)
[        ] WARN:  at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:75)
[        ] WARN:  at yugecin.opsudance.OpsuDance.start(OpsuDance.java:53)
[        ] WARN:  at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)`

4. after all that. the skin im trying to load does not load, since opsu does not support mp3.

**Comment by yugecin** [comment]
then don't use it, my interest in osu things are gone anyways and this hasn't had a decent update in 1.5 years

5 can probably be solved by disabling "dance storyboard" in the options

**Comment by piee-kun** [comment]
thing is, i need it for its capabilities. im planning on making a semi-natural auto played for footage recording, and osu!fx does too many tricks when going to sliders. messes with the nice flow of shorter sliders.
