### ISSUE TITLE
getting error at start

### ISSUE THREAD

**Issue by nissanwarrior69** [yugecin/opsu-dance#33]
Tue Oct 11 17:09:18 PDT 2016 ERROR:opsu! could not be launched for one of these reasons:
- An instance of opsu! is already running.
- Another program is bound to port 49250. You can change the port opsu! uses by editing the "Port" field in the configuration file.
Tue Oct 11 17:11:34 PDT 2016 ERROR:Pixel format not accelerated
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.newdawn.slick.AppGameContainer.tryCreateDisplay(AppGameContainer.java:302)
	at org.newdawn.slick.AppGameContainer.access$000(AppGameContainer.java:34)
	at org.newdawn.slick.AppGameContainer$2.run(AppGameContainer.java:367)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:348)
	at itdelatrisu.opsu.Container.start(Container.java:61)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:204)
Tue Oct 11 17:11:35 PDT 2016 ERROR:** Uncaught Exception! **
Tue Oct 11 17:11:35 PDT 2016 ERROR:null
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:652)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:590)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:307)
	at itdelatrisu.opsu.Container.close_sub(Container.java:113)
	at itdelatrisu.opsu.Container.start(Container.java:67)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:204)

**Comment by nissanwarrior69** [comment]
there is no other opsu running at all

**Comment by yugecin** [comment]
Try changing the port in the .cfg file

**Comment by nissanwarrior69** [comment]
I did and it still giving me a error but not a port error

**Comment by Swimgiant** [comment]
I am getting this issue with the port as well even if I change the port

**Comment by nissanwarrior69** [comment]
Ok then

**Comment by yugecin** [comment]
If it still happens, edit the .opsu.cfg and set:
```NoSingleInstance = true```

**Comment by nissanwarrior69** [comment]
Ok
