### ISSUE TITLE
*** Unhandled NullPointerException: update/render error

### ISSUE THREAD

**Issue by NameTheWorst** [yugecin/opsu-dance#335]
update/render error

**ver** 0.5.2
**os** Windows 10 (amd64)
**jre** 1.8.0_231 (Oracle Corporation)
**trace**
```
java.lang.NullPointerException
	at yugecin.opsudance.ui.OptionsOverlay.renderSearch(OptionsOverlay.java:704)
	at yugecin.opsudance.ui.OptionsOverlay.render(OptionsOverlay.java:336)
	at itdelatrisu.opsu.states.game.Game.render(Game.java:733)
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:281)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:75)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:53)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: 4.6.13587 Compatibility Profile Context 20.2.2 26.20.15019.19000(ATI Technologies Inc.)
state is Game
> BaseOpsuState dump
isDirty: false
> Game dump
beatmap:  setid 1046876 beatmapid 2202224 name nana(Sevencolors) - chameleon [Ojou]
objectidx: 0
time: 0ms
< DisplayContainer
tNextState is null
loading sound: none
playing map:  setid 1046876 beatmapid 2202224 name nana(Sevencolors) - chameleon [Ojou]
 at time 0 

```

**Comment by yugecin** [comment]
disable some "storyboard" option
