### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by nissanwarrior69** [yugecin/opsu-dance#34]
**Version:** 0.2.0
**Build date:** 2016-10-04 15:22
**OS:** Windows 7 (amd64)
**JRE:** 1.8.0_101
**Error:** `** Uncaught Exception! **`
**Stack trace:**

```
java.lang.NullPointerException
    at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:652)
    at itdelatrisu.opsu.GameImage.getImage(GameImage.java:590)
    at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:307)
    at itdelatrisu.opsu.Container.close_sub(Container.java:113)
    at itdelatrisu.opsu.Container.start(Container.java:67)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:204)
```

**Comment by yugecin** [comment]
how, why, when?
try changing the skin option in .opsu.cfg to ```Default``` and see if it still happens

**Comment by nissanwarrior69** [comment]
Ok

**Comment by nissanwarrior69** [comment]
i changed the skin to Default in .opsu.cfg and it is still giving errors

**Comment by yugecin** [comment]
Is there an other error? I have the feeling like this is an error when the game is closing because of an other problem

**Comment by nissanwarrior69** [comment]
Nope those are the only errors i get

**Comment by yugecin** [comment]
incorrect stacktrace by old code, cant do much here.
next release (0.3.0) will show the correct cause
