### ISSUE TITLE
*** Unhandled NullPointerException: update/render error

### ISSUE THREAD

**Issue by MichaelNotITG** [yugecin/opsu-dance#363]
update/render error

**ver** 0.5.2
**os** Windows 10 (amd64)
**jre** 1.8.0_281 (Oracle Corporation)
**trace**
```
java.lang.NullPointerException
	at yugecin.opsudance.ui.OptionsOverlay.renderSearch(OptionsOverlay.java:704)
	at yugecin.opsudance.ui.OptionsOverlay.render(OptionsOverlay.java:336)
	at itdelatrisu.opsu.states.game.Game.render(Game.java:733)
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:281)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:75)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:53)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: 4.4.0 - Build 20.19.15.4835(Intel)
state is Game
> BaseOpsuState dump
isDirty: false
> Game dump
beatmap:  setid 884669 beatmapid 1849131 name LeaF - Aleph-0 [Jack of all Trades]
objectidx: 0
time: 398ms
< DisplayContainer
tNextState is null
loading sound: none
playing map:  setid 884669 beatmapid 1849131 name LeaF - Aleph-0 [Jack of all Trades]
 at time 398 

```

**Comment by yugecin** [comment]
try disabling the "storyboard editor" option in the option menu
