### ISSUE TITLE
*** Unhandled UnsupportedAudioFileException: Failed to load clip C:\Users\user\AppData\Local\osu!\Skins\AimAssistSkin\applause.wav

### ISSUE THREAD

**Issue by WNnitro5555** [yugecin/opsu-dance#371]
Failed to load clip C:\Users\user\AppData\Local\osu!\Skins\AimAssistSkin\applause.wav

**ver** 0.5.2
**os** Windows 10 (amd64)
**jre** 1.8.0_291 (Oracle Corporation)
**trace**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:103)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:226)
	at yugecin.opsudance.skinning.SkinService.reloadSkin(SkinService.java:46)
	at yugecin.opsudance.options.Options$10.clickListItem(Options.java:201)
	at yugecin.opsudance.ui.OptionsOverlay$MyDropdownMenu.itemSelected(OptionsOverlay.java:1390)
	at itdelatrisu.opsu.ui.DropdownMenu.mouseReleased(DropdownMenu.java:289)
	at yugecin.opsudance.core.input.Input.dispatch(Input.java:199)
	at yugecin.opsudance.core.input.Input.poll(Input.java:127)
	at yugecin.opsudance.core.DisplayContainer.run(DisplayContainer.java:220)
	at yugecin.opsudance.OpsuDance.rungame(OpsuDance.java:75)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:53)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: 4.0.0 - Build 10.18.10.5161(Intel)
state is MainMenu
> BaseOpsuState dump
isDirty: false
> MainMenu dump
< DisplayContainer
tNextState is null
overlay MainMenu
> options overlay is active
hoverOption is Skin
< DisplayContainerloading sound: C:\Users\user\AppData\Local\osu!\Skins\AimAssistSkin\applause.wav, progress: 0
playing map:  setid 522857 beatmapid 1110281 name Porter Robinson & Madeon - Shelter [Alone Together]
 at time 184696 

```

**Comment by amandabruh** [comment]
lmao aimassistskin using taiko aim assist lmao
