### ISSUE TITLE
*** Unhandled UnsupportedAudioFileException: Failed to load clip D:\osu!\Skins\Xact U\combobreak.mp3

### ISSUE THREAD

**Issue by secretboss42542** [yugecin/opsu-dance#376]
PASTE THE DUMP HEREFailed to load clip D:\osu!\Skins\Xact U\combobreak.mp3

**ver** 0.5.2
**os** Windows 10 (amd64)
**jre** 1.8.0_291 (Oracle Corporation)
**trace**
```
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:103)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:226)
	at itdelatrisu.opsu.states.Splash$1.run(Splash.java:87)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: 4.6.0 - Build 27.20.100.8783(Intel)
state is Splash
> BaseOpsuState dump
isDirty: false
> Splash dump
progress: initing sound
< DisplayContainer
tNextState is null
loading sound: D:\osu!\Skins\Xact U\combobreak.mp3, progress: 2
playing map: null

```

**Comment by secretboss42542** [comment]
help pls
