### ISSUE TITLE
Some times when i try to make a dance storyboard it crashes when changing the mover algorithm w/ a lower speed 

### ISSUE THREAD

**Issue by Name-The-Best** [yugecin/opsu-dance#79]
heres the error `Something bad happend while playing
java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
	at java.util.LinkedList.checkElementIndex(Unknown Source)
	at java.util.LinkedList.get(Unknown Source)
	at awlex.ospu.polymover.factory.PolyMoverFactory.update(PolyMoverFactory.java:81)
	at yugecin.opsudance.Dancer.createNewMover(Dancer.java:265)
	at yugecin.opsudance.Dancer.setMoverFactoryIndex(Dancer.java:160)
	at itdelatrisu.opsu.Options$GameOption$31.clickListItem(Options.java:606)
	at yugecin.opsudance.ui.OptionsOverlay$1.update(OptionsOverlay.java:149)
	at yugecin.opsudance.ui.ItemList.mouseReleased(ItemList.java:119)
	at yugecin.opsudance.ui.OptionsOverlay.mouseReleased(OptionsOverlay.java:192)
	at yugecin.opsudance.ui.SBOverlay.mouseReleased(SBOverlay.java:231)
	at itdelatrisu.opsu.states.Game.mouseReleased(Game.java:1227)
	at org.newdawn.slick.state.StateBasedGame.mouseReleased(StateBasedGame.java:510)
	at org.newdawn.slick.Input.poll(Input.java:1272)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:96)
	at itdelatrisu.opsu.Container.start(Container.java:66)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:206)
`

**Comment by Chaaoos** [comment]
Yeah happened to me too, was about to make a issue
