### ISSUE TITLE
Crash after selecting this https://osu.ppy.sh/s/182597

### ISSUE THREAD

**Issue by ModiFlasher** [yugecin/opsu-dance#92]
Heres log 

```
Failed to destroy OpenAL.
org.newdawn.slick.SlickException: Could not clear SoundStore sources, err: 40964
	at itdelatrisu.opsu.audio.MusicController.destroyOpenAL(MusicController.java:449)
	at itdelatrisu.opsu.audio.MusicController.reset(MusicController.java:411)
	at itdelatrisu.opsu.audio.MusicController.play(MusicController.java:100)
	at itdelatrisu.opsu.states.SongMenu.setFocus(SongMenu.java:1410)
	at itdelatrisu.opsu.states.SongMenu.mouseClicked(SongMenu.java:902)
	at org.newdawn.slick.state.StateBasedGame.mouseClicked(StateBasedGame.java:488)
	at org.newdawn.slick.Input.fireMouseClicked(Input.java:1563)
	at org.newdawn.slick.Input.considerDoubleClick(Input.java:1141)
	at org.newdawn.slick.Input.poll(Input.java:1265)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:680)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:96)
	at itdelatrisu.opsu.Container.start(Container.java:66)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:206)
```

**Comment by yugecin** [comment]
the audio file for that map is invalid, both vlc and winamp can't even play it. cannot do much here

**Comment by ModiFlasher** [comment]
Hmmm okay but i can play it with aimp maybe cuz audio codec not supported
