### ISSUE TITLE
game crashes after finishing level

### ISSUE THREAD

**Issue by AwesomeGamer89** [yugecin/opsu-dance#98]
error code:

ERROR:Game.update() failure.
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:96)
	at itdelatrisu.opsu.Container.start(Container.java:66)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:206)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 143
	at awlex.ospu.polymover.factory.PolyMoverFactory.create(PolyMoverFactory.java:68)
	at yugecin.opsudance.Dancer.createNewMover(Dancer.java:267)
	at yugecin.opsudance.Dancer.setMoverFactoryIndex(Dancer.java:160)
	at itdelatrisu.opsu.Options$GameOption$31.read(Options.java:622)
	at yugecin.opsudance.ui.SBOverlay.leave(SBOverlay.java:267)
	at itdelatrisu.opsu.states.Game.leave(Game.java:1481)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:243)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
)

**Comment by yugecin** [comment]
any specific map?
